<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Accion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Accion_model');
    } 

    /*
     * Listing of accion
     */
    function index()
    {
        $data['accion'] = $this->Accion_model->get_all_accion();
        
        $data['_view'] = 'accion/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new accion
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nombre' => $this->input->post('nombre'),
            );
            
            $accion_id = $this->Accion_model->add_accion($params);
            redirect('accion/index');
        }
        else
        {            
            $data['_view'] = 'accion/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a accion
     */
    function edit($id)
    {   
        // check if the accion exists before trying to edit it
        $data['accion'] = $this->Accion_model->get_accion($id);
        
        if(isset($data['accion']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nombre' => $this->input->post('nombre'),
                );

                $this->Accion_model->update_accion($id,$params);            
                redirect('accion/index');
            }
            else
            {
                $data['_view'] = 'accion/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The accion you are trying to edit does not exist.');
    } 

    /*
     * Deleting accion
     */
    function remove($id)
    {
        $accion = $this->Accion_model->get_accion($id);

        // check if the accion exists before trying to delete it
        if(isset($accion['id']))
        {
            $this->Accion_model->delete_accion($id);
            redirect('accion/index');
        }
        else
            show_error('The accion you are trying to delete does not exist.');
    }
    
}
