<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Carga_manual extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Carga_manual_model');
    } 

    /*
     * Listing of cargas_manuales
     */
    function index()
    {
        $data['cargas_manuales'] = $this->Carga_manual_model->get_all_cargas_manuales();
        
        $data['_view'] = 'carga_manual/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new carga_manual
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('monto','Monto','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'proveedor_cuenta_id' => $this->input->post('proveedor_cuenta_id'),
				'monto' => $this->input->post('monto'),
				'fecha_alta' => $this->input->post('fecha_alta'),
				'fecha_modif' => $this->input->post('fecha_modif'),
				'comentario' => $this->input->post('comentario'),
            );
            
            $carga_manual_id = $this->Carga_manual_model->add_carga_manual($params);
            redirect('carga_manual/index');
        }
        else
        {
			$this->load->model('Proveedor_cuentum_model');
			$data['all_proveedor_cuenta'] = $this->Proveedor_cuentum_model->get_all_proveedor_cuenta();
            
            $data['_view'] = 'carga_manual/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a carga_manual
     */
    function edit($id)
    {   
        // check if the carga_manual exists before trying to edit it
        $data['carga_manual'] = $this->Carga_manual_model->get_carga_manual($id);
        
        if(isset($data['carga_manual']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('monto','Monto','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'proveedor_cuenta_id' => $this->input->post('proveedor_cuenta_id'),
					'monto' => $this->input->post('monto'),
					'fecha_alta' => $this->input->post('fecha_alta'),
					'fecha_modif' => $this->input->post('fecha_modif'),
					'comentario' => $this->input->post('comentario'),
                );

                $this->Carga_manual_model->update_carga_manual($id,$params);            
                redirect('carga_manual/index');
            }
            else
            {
				$this->load->model('Proveedor_cuentum_model');
				$data['all_proveedor_cuenta'] = $this->Proveedor_cuentum_model->get_all_proveedor_cuenta();

                $data['_view'] = 'carga_manual/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The carga_manual you are trying to edit does not exist.');
    } 

    /*
     * Deleting carga_manual
     */
    function remove($id)
    {
        $carga_manual = $this->Carga_manual_model->get_carga_manual($id);

        // check if the carga_manual exists before trying to delete it
        if(isset($carga_manual['id']))
        {
            $this->Carga_manual_model->delete_carga_manual($id);
            redirect('carga_manual/index');
        }
        else
            show_error('The carga_manual you are trying to delete does not exist.');
    }
    
}
