<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        
    }

    function index()
    {
        $this->load->model('Mensaje_model');
        $this->load->library('session');
        if(!$this->session->userdata('user_name'))
        {
            redirect('acceso/index');
        }
        $id_usuario = $this->session->userdata('id_usuario'); 
        $data['mensajes'] = $this->Mensaje_model->get_mensajes_recibidos($id_usuario);
        switch ($this->session->userdata('privileges'))
        {
            case 'root':
                $data['_view'] = 'dashboard';
                break;
            case 'admin':
                $data['_view'] = 'dashboard';
                break;
            case 'gerente':
               $data['_view'] = 'dashboard_gerente';
                break;
            case 'sucursal':
                $data['_view'] = 'dashboard_sucursal';
                break;
            
            default :
                $data['_menu'] = 'dashboard';
                break;
        }
        //$data['_view'] = 'dashboard';
        $this->load->view('layouts/main',$data);
    }
}
