<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Departamento extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Departamento_model');
    } 

    /*
     * Listing of departamento
     */
    function index()
    {
        $data['departamento'] = $this->Departamento_model->get_all_departamento();
        
        $data['_view'] = 'departamento/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new departamento
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nombre' => $this->input->post('nombre'),
				'provincia_id' => $this->input->post('provincia_id'),
            );
            
            $departamento_id = $this->Departamento_model->add_departamento($params);
            redirect('departamento/index');
        }
        else
        {            
            $data['_view'] = 'departamento/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a departamento
     */
    function edit($id)
    {   
        // check if the departamento exists before trying to edit it
        $data['departamento'] = $this->Departamento_model->get_departamento($id);
        
        if(isset($data['departamento']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nombre' => $this->input->post('nombre'),
					'provincia_id' => $this->input->post('provincia_id'),
                );

                $this->Departamento_model->update_departamento($id,$params);            
                redirect('departamento/index');
            }
            else
            {
                $data['_view'] = 'departamento/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The departamento you are trying to edit does not exist.');
    } 

    /*
     * Deleting departamento
     */
    function remove($id)
    {
        $departamento = $this->Departamento_model->get_departamento($id);

        // check if the departamento exists before trying to delete it
        if(isset($departamento['id']))
        {
            $this->Departamento_model->delete_departamento($id);
            redirect('departamento/index');
        }
        else
            show_error('The departamento you are trying to delete does not exist.');
    }
    
}
