<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Documento_iva extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Documento_iva_model');
        $this->load->model('Historial_accion_model');
    } 

    /*
     * Listing of documento_iva
     */
    function index()
    {
        $data['documento_iva'] = $this->Documento_iva_model->get_all_documento_iva();
        
        $data['_view'] = 'documento_iva/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new documento_iva
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('monto','Monto','required');
		$this->form_validation->set_rules('porcentaje','Porcentaje','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'documento_id' => $this->input->post('documento_id'),
				'monto' => $this->input->post('monto'),
				'porcentaje' => $this->input->post('porcentaje'),
            );
            
            $documento_iva_id = $this->Documento_iva_model->add_documento_iva($params);
            redirect('documento_iva/index');
        }
        else
        {
			$this->load->model('Documento_model');
			$data['all_documentos'] = $this->Documento_model->get_all_documentos();
            
            $data['_view'] = 'documento_iva/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a documento_iva
     */
    function edit($id)
    {   
        // check if the documento_iva exists before trying to edit it
        $data['documento_iva'] = $this->Documento_iva_model->get_documento_iva($id);
        
        if(isset($data['documento_iva']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('monto','Monto','required');
			$this->form_validation->set_rules('porcentaje','Porcentaje','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'documento_id' => $this->input->post('documento_id'),
					'monto' => $this->input->post('monto'),
					'porcentaje' => $this->input->post('porcentaje'),
                );

                $this->Documento_iva_model->update_documento_iva($id,$params);            
                redirect('documento_iva/index');
            }
            else
            {
				$this->load->model('Documento_model');
				$data['all_documentos'] = $this->Documento_model->get_all_documentos();

                $data['_view'] = 'documento_iva/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The documento_iva you are trying to edit does not exist.');
    } 

    /*
     * Deleting documento_iva
     */
    function remove($id)
    {
        $documento_iva = $this->Documento_iva_model->get_documento_iva($id);

        // check if the documento_iva exists before trying to delete it
        if(isset($documento_iva['id']))
        {
            $this->Documento_iva_model->delete_documento_iva($id);
            redirect('documento_iva/index');
        }
        else
            show_error('The documento_iva you are trying to delete does not exist.');
    }
    
}
