<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Informe extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Informes_model');
        
    } 
    
//    function informe_iva_ventas()
//    {
//        $data['_view'] = 'informes/seleccion_periodo_informe_venta';
//        $data['js_to_load'] = ['seleccionar_periodo_iva_c.js'];
//        $this->load->view("layouts/main",$data);
//    }
    
    function informe_periodo()
    {
        $data['_view'] = 'informes/informe_resumen_periodo';
        $data['js_to_load'] = ['informe_resumen_periodo.js'];
        $this->load->view("layouts/main",$data);
    }
    
    function get_informe_periodo($d,$m,$a)
    {
        
        $data['rows'] = $this->Informes_model->obtener_informe_periodo($a."-".$m."-".$d);
        $data['periodo'] = $d."-".$m."-".$a;
        $this->load->view("informes/_datos_informe_periodo",$data);
    }


    function descargar_informe()
    {
        $json = $this->input->post("json");
        $now = new DateTime();
        $filename = "informe_iva_c_". $now->getTimestamp().'.csv';
        header('Content-type: text/plain');

        // It will be called report.txt
        header('Content-Disposition: attachment; filename="'.$filename.'"');
        print ($text); 
    }
    
    function informe_iva()
    {
        $data['_view'] = 'informes/seleccion_periodo_informe';
        $data['js_to_load'] = ['seleccionar_periodo_iva_c.js'];
        $this->load->view("layouts/main",$data);
                
    }
    
}