<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Notum extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Notum_model');
    } 

    /*
     * Listing of nota
     */
    function index()
    {
        $data['nota'] = $this->Notum_model->get_all_nota();
        
        $data['_view'] = 'notum/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new notum
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'proveedor_cuenta_id' => $this->input->post('proveedor_cuenta_id'),
				'fecha' => $this->input->post('fecha'),
				'mensaje' => $this->input->post('mensaje'),
            );
            
            $notum_id = $this->Notum_model->add_notum($params);
            redirect('notum/index');
        }
        else
        {            
            $data['_view'] = 'notum/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a notum
     */
    function edit($id)
    {   
        // check if the notum exists before trying to edit it
        $data['notum'] = $this->Notum_model->get_notum($id);
        
        if(isset($data['notum']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'proveedor_cuenta_id' => $this->input->post('proveedor_cuenta_id'),
					'fecha' => $this->input->post('fecha'),
					'mensaje' => $this->input->post('mensaje'),
                );

                $this->Notum_model->update_notum($id,$params);            
                redirect('notum/index');
            }
            else
            {
                $data['_view'] = 'notum/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The notum you are trying to edit does not exist.');
    } 

    /*
     * Deleting notum
     */
    function remove($id)
    {
        $notum = $this->Notum_model->get_notum($id);

        // check if the notum exists before trying to delete it
        if(isset($notum['id']))
        {
            $this->Notum_model->delete_notum($id);
            redirect('notum/index');
        }
        else
            show_error('The notum you are trying to delete does not exist.');
    }
    
}
