<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Proveedor_cuentum extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Proveedor_cuentum_model');
    } 

    function ObtenerCuenta($tipo, $prov_id)
    {
        
    }
    
    function CrearCuenta($tipo, $prov_id)
    {
        
    }
    
    /*
     * Listing of proveedor_cuenta
     */
    function index()
    {
        $data['proveedor_cuenta'] = $this->Proveedor_cuentum_model->get_all_proveedor_cuenta();
        
        $data['_view'] = 'proveedor_cuentum/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new proveedor_cuentum
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'proveedor_id' => $this->input->post('proveedor_id'),
				'fecha_modif' => $this->input->post('fecha_modif'),
				'saldo' => $this->input->post('saldo'),
				'nro_cuenta' => $this->input->post('nro_cuenta'),
				'comentarios' => $this->input->post('comentarios'),
            );
            
            $proveedor_cuentum_id = $this->Proveedor_cuentum_model->add_proveedor_cuentum($params);
            redirect('proveedor_cuentum/index');
        }
        else
        {            
            $data['_view'] = 'proveedor_cuentum/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a proveedor_cuentum
     */
    function edit($id)
    {   
        // check if the proveedor_cuentum exists before trying to edit it
        $data['proveedor_cuentum'] = $this->Proveedor_cuentum_model->get_proveedor_cuentum($id);
        
        if(isset($data['proveedor_cuentum']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'proveedor_id' => $this->input->post('proveedor_id'),
					'fecha_modif' => $this->input->post('fecha_modif'),
					'saldo' => $this->input->post('saldo'),
					'nro_cuenta' => $this->input->post('nro_cuenta'),
					'comentarios' => $this->input->post('comentarios'),
                );

                $this->Proveedor_cuentum_model->update_proveedor_cuentum($id,$params);            
                redirect('proveedor_cuentum/index');
            }
            else
            {
                $data['_view'] = 'proveedor_cuentum/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The proveedor_cuentum you are trying to edit does not exist.');
    } 

    /*
     * Deleting proveedor_cuentum
     */
    function remove($id)
    {
        $proveedor_cuentum = $this->Proveedor_cuentum_model->get_proveedor_cuentum($id);

        // check if the proveedor_cuentum exists before trying to delete it
        if(isset($proveedor_cuentum['id']))
        {
            $this->Proveedor_cuentum_model->delete_proveedor_cuentum($id);
            redirect('proveedor_cuentum/index');
        }
        else
            show_error('The proveedor_cuentum you are trying to delete does not exist.');
    }
    
}
