<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Recibo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Recibo_model');
    } 
    
    function anular_recibo($id)
    {
        header('Content-type: application/json');
        
        try{
            $this->Recibo_model->anular_recibo($id);
            $results = array(
                'status' => 'success'
             );
            echo json_encode($results);
        }
        catch (Exception $e)
        {
            $results = array(
                'error' => true,
                'error_msg' => $e->getMessage()
             );
            echo json_encode($results);
        }
    }

    function detalle_recibo($id)
    {
        $data['js_to_load'] = ['modal.js','recibo_detalle.js'];
        $data['recibo'] = $this->Recibo_model->obtener_recibo($id);
        $data['_view'] = 'recibo/recibo_detalle';
        $this->load->view('layouts/main',$data);
    }
    
    function nuevo_recibo()
    {
        $this->load->model('Proveedor_model');
        $this->load->model('Historial_accion_model');
        $data['proveedores'] = $this->Proveedor_model->get_all_proveedor();
        $data['js_to_load'] = 'recibo_nuevo.js';
        $this->load->library('form_validation');
        $this->load->library('session');
        $this->load->helper('date_helper');
        
        $this->form_validation->set_rules('fkPago','fkPago','required');
        $this->form_validation->set_rules('nro_recibo','nro_recibo','required');
        $this->form_validation->set_rules('fkProveedor','fkProveedor','required');
 
        if($this->form_validation->run()!==false)     
        {   
            $params = array(
				'fkProveedor' => $this->input->post('fkProveedor'),
				'monto' => $this->input->post('monto'),
				'nro_recibo' => $this->input->post('nro_recibo'),
                                'fkPago' => $this->input->post('fkPago'),
                                'fecha' => parse_date($this->input->post('fecha')),
                                'fkUsuario' => $this->session->userdata('id_usuario')
            );
            
            $recibo_id = $this->Recibo_model->add_recibo($params);
            
            $this->Historial_accion_model->registrar_evento(
                    $this->session->userdata('id_usuario'),
                    'RECIBO_ADD',
                    '-',
                    $recibo_id
                    );
            
            redirect('proveedor/details/'.$this->input->post('fkProveedor'));
        }
        else
        {
            $data['_view'] = 'recibo/nuevo_recibo';
            $this->load->view('layouts/main',$data);
        }
    }
    
    function listado_recibos()
    {
        //pagination
        $pagination_params['limit'] = RECORDS_PER_PAGE; 
        $pagination_params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('recibo/listado_recibos?');
        $config['total_rows'] = $this->Recibo_model->get_recibos_count();
        $this->pagination->initialize($config);
        
        $data['recibos'] = $this->Recibo_model->get_listado($pagination_params);
        $data['_view'] = 'recibo/listado_recibos';
        $this->load->view('layouts/main',$data);
    }


    function get_pagos_proveedor($idProveedor)
    {
        $data['pagos']= $this->Recibo_model->get_pagos_proveedor($idProveedor);
        
        $this->load->view('recibo/_seleccion_pago',$data);
    }
    
    
    
}