<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Carga_manual_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get carga_manual by id
     */
    function get_carga_manual($id)
    {
        return $this->db->get_where('carga_manual',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all cargas_manuales
     */
    function get_all_cargas_manuales()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('carga_manual')->result_array();
    }
        
    /*
     * function to add new carga_manual
     */
    function add_carga_manual($params)
    {
        $this->db->insert('carga_manual',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update carga_manual
     */
    function update_carga_manual($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('carga_manual',$params);
    }
    
    /*
     * function to delete carga_manual
     */
    function delete_carga_manual($id)
    {
        return $this->db->delete('carga_manual',array('id'=>$id));
    }
}
