<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Documento_iva_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get documento_iva by id
     */
    function get_documento_iva($id)
    {
        return $this->db->get_where('documento_iva',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all documento_iva
     */
    function get_all_documento_iva()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('documento_iva')->result_array();
    }
        
    /*
     * function to add new documento_iva
     */
    function add_documento_iva($params)
    {
        $this->db->insert('documento_iva',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update documento_iva
     */
    function update_documento_iva($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('documento_iva',$params);
    }
    
    /*
     * function to delete documento_iva
     */
    function delete_documento_iva($id)
    {
        return $this->db->delete('documento_iva',array('id'=>$id));
    }
}
