<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Documento_percepcion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get documento_percepcion by id
     */
    function get_documento_percepcion($id)
    {
        return $this->db->get_where('documento_percepcion',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all documento_percepciones
     */
    function get_all_documento_percepciones()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('documento_percepcion')->result_array();
    }
        
    /*
     * function to add new documento_percepcion
     */
    function add_documento_percepcion($params)
    {
        $this->db->insert('documento_percepcion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update documento_percepcion
     */
    function update_documento_percepcion($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('documento_percepcion',$params);
    }
    
    /*
     * function to delete documento_percepcion
     */
    function delete_documento_percepcion($id)
    {
        return $this->db->delete('documento_percepcion',array('id'=>$id));
    }
}
