<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Historial_accion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    function registrar_evento($usuario_id,$tipo_accion,$detalle,$rel_id){
        $params=array(
            'usuario_id' => $usuario_id,
            'tipo_accion' => $tipo_accion,
            'detalle' => $detalle,
            'rel_id' => $rel_id
        );
        $this->db->insert('historial_accion',$params);
    }


    /*
     * Get historial_accion by id
     */
    function get_historial_accion($id)
    {
        return $this->db->get_where('historial_accion',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all historial_accion
     */
    function get_all_historial_accion()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('historial_accion')->result_array();
    }
        
    /*
     * function to add new historial_accion
     */
    function add_historial_accion($params)
    {
        $this->db->insert('historial_accion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update historial_accion
     */
    function update_historial_accion($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('historial_accion',$params);
    }
    
    /*
     * function to delete historial_accion
     */
    function delete_historial_accion($id)
    {
        return $this->db->delete('historial_accion',array('id'=>$id));
    }
}
