<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Informes_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    function obtener_informe_periodo($periodo)
    {
        return $this->db->query(
                "select 
                    t.*,
                    (t.debe - t.haber) as 'saldo'
                    from(
                    select 
                            p.id,
                            p.nombre as 'proveedor',
                            sum(if(docs.tipo = 'd', docs.monto, 0)) as 'debe',
                            sum(if(docs.tipo = 'h', docs.monto, 0)) as 'haber'
                     from (
                            select 
                                    d.id,
                                    'd' as 'tipo',
                                    d.monto_total as 'monto',
                                    d.fkProveedor as 'fk_prov'
                            from documento d where date(d.fecha_carga) <= date('$periodo') and d.anulado=0
                            union 
                            select 
                                    pp.id,
                                    'h' as 'tipo',
                                    pp.monto as 'monto',
                                    pp.fkProveedor as 'fk_prov'
                            from 
                            pago_proveedor pp  where date(pp.fecha) <= date('$periodo')
                    ) as docs,
                    proveedor p
                    where p.id = docs.fk_prov 
                    group by docs.fk_prov
                    ) as t;
                "
                )->result_array();
    }
}