<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Localidad_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get localidad by id
     */
    function get_localidad($id)
    {
        return $this->db->get_where('localidad',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all localidad
     */
    function get_all_localidad()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('localidad')->result_array();
    }
        
    /*
     * function to add new localidad
     */
    function add_localidad($params)
    {
        $this->db->insert('localidad',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update localidad
     */
    function update_localidad($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('localidad',$params);
    }
    
    /*
     * function to delete localidad
     */
    function delete_localidad($id)
    {
        return $this->db->delete('localidad',array('id'=>$id));
    }
}
