<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Notum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get notum by id
     */
    function get_notum($id)
    {
        return $this->db->get_where('nota',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all nota
     */
    function get_all_nota()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('nota')->result_array();
    }
        
    /*
     * function to add new notum
     */
    function add_notum($params)
    {
        $this->db->insert('nota',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update notum
     */
    function update_notum($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('nota',$params);
    }
    
    /*
     * function to delete notum
     */
    function delete_notum($id)
    {
        return $this->db->delete('nota',array('id'=>$id));
    }
}
