<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Proveedor_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    function cuit_exists($cuit)
    {
        $result = $this->db->query("select p.id from proveedor p where p.cuit='".$cuit."';")->result_array();
        return sizeof($result)>0;
    }
    
    /*
     * Get proveedor by id
     */
    function get_proveedor($id)
    {
        return $this->db->get_where('proveedor',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all proveedor
     */
    function get_all_proveedor()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('proveedor')->result_array();
    }
        
    /*
     * function to add new proveedor
     */
    function add_proveedor($params)
    {
        $this->db->insert('proveedor',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update proveedor
     */
    function update_proveedor($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('proveedor',$params);
    }
    
    /*
     * function to delete proveedor
     */
    function delete_proveedor($id)
    {
        return $this->db->delete('proveedor',array('id'=>$id));
    }
}
