<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Provincium_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get provincium by id
     */
    function get_provincium($id)
    {
        return $this->db->get_where('provincia',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all provincias
     */
    function get_all_provincias()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('provincia')->result_array();
    }
        
    /*
     * function to add new provincium
     */
    function add_provincium($params)
    {
        $this->db->insert('provincia',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update provincium
     */
    function update_provincium($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('provincia',$params);
    }
    
    /*
     * function to delete provincium
     */
    function delete_provincium($id)
    {
        return $this->db->delete('provincia',array('id'=>$id));
    }
}
