<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Recibo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    function anular_recibo($idRecibo)
    {
        $this->db->query("update recibo r set r.anulado=1 where r.id=".$idRecibo.";");
    }


    function obtener_recibo($idRecibo)
    {
        return $this->
                db->
                query
                (
                        "
                        select 
                        r.id,
                        r.nro_recibo,
                        r.monto,
                        date_format(r.fecha,'%d/%m/%Y') as 'fecha',
                        p.nombre as 'proveedor',
                        r.anulado
                        from 
                        recibo r ,
                        proveedor p
                        where 
                        r.fkProveedor = p.id and
                        r.id=".$idRecibo.";"
                        )
                ->row_array();
                
    }
    
    function get_listado($params)
    {
        $limit = 9999999;$offset=0;
        if(isset($params))
        {
            $limit = $params['limit'];
            $offset = $params['offset'];
        }
        
        return $this->db->query(
                "select 
                date_format(r.fecha,'%d/%m/%Y') as 'fecha', r.nro_recibo, r.fkProveedor,r.fkPago, r.anulado,r.id,
                 replace(format(r.monto,2),',','') as 'monto', 
                p.nombre as 'proveedor'
                 from recibo r, proveedor p where p.id = r.fkProveedor order by r.id desc limit " . $offset . "," . $limit .  ";"
                )->result_array();
    }
    
    function get_recibos_count()
    {
        $this->db->from('recibo');
        return $this->db->count_all_results();
    }
    
    function get_pagos_proveedor($idProveedor)
    {
        return $this->db->query("
            select 
                pp.id, 
                pp.monto, 
                date_format( pp.fecha_alta , '%d/%m/%y') as 'fecha'       
            from 
                pago_proveedor pp , 
                proveedor_cuenta pc
            where        
                pp.proveedor_cuenta_id = pc.id and 
                pc.proveedor_id = ".$idProveedor.
                "  and pp.id not in (
                select r.fkPago from recibo r
                ); ")->result_array();
    }
    
    function add_recibo($params)
    {
        $this->db->insert('recibo',$params);
        return $this->db->insert_id();
    }
}
